metadata:
  config_instance_name: separator1_grid_search_4ports_hd64_stages2_depth3_share1_default_nmse
  model_config_name: separator1_grid_search_4ports
  timestamp: '2025-12-12T17:27:06.478460'
  training_config_name: default_nmse
  training_duration: 22.761244773864746
model_config:
  activation_type: relu
  hidden_dim: 64
  mlp_depth: 3
  model_type: separator1
  num_params: 52320
  num_ports: 4
  num_stages: 2
  pos_values:
  - 0
  - 3
  - 6
  - 9
  seq_len: 12
  share_weights_across_stages: true
training_config:
  batch_size: 4096
  learning_rate: 0.01
  loss_type: nmse
  num_batches: 100
  snr_config:
    max: 30
    min: 0
    num_bins: 10
    per_sample: true
    sampling: stratified
    type: range
  tdl_config:
  - A-30
  - B-100
  - C-300
