model_spec:
  seq_len: 12
  model_type: separator1
  pos_values:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  mlp_depth: 3
  share_weights_across_stages: false
  hidden_dim: 64
  num_stages: 2
  num_ports: 6
  normalize_energy: true
  activation_type: relu
  onnx_mode: false
  num_params: 156960
training_spec:
  loss_type: log
  learning_rate: 0.01
  num_batches: 100000
  batch_size: 4096
  snr_config:
    type: range
    min: 0
    max: 30
    per_sample: true
    sampling: stratified
    num_bins: 10
  tdl_config:
  - A-30
  - B-100
  - C-300
  print_interval: 100
  validation_interval: 100
  validation_batches: 4
  early_stop_loss: null
  patience: 5
  keep_last_n_checkpoints: 2
  save_interval: 1000
  lr_scheduler:
    enabled: true
    factor: 0.8
    patience: 30
    threshold: 0.005
    threshold_mode: abs
    cooldown: 10
    min_lr: 1.0e-06
metadata:
  experiment_name: default_6port_separator1
  model_recipe_name: separator1_grid_search_6ports
  model_label: separator1_grid_search_6ports_hd64_stages2_depth3_share0
  run_name: separator1_grid_search_6ports_hd64_stages2_depth3_share0
  training_recipe_name: snr_range_0_30_perSample
  training_label: snr_range_0_30_perSample
  training_duration: 1322.5442605018616
  timestamp: '2026-04-14T08:19:46.798858'
