metadata:
  config_instance_name: separator1_grid_search_6ports_hd64_stages2_depth3_share1_snr_range_0_30_perSample_nmse
  model_config_name: separator1_grid_search_6ports
  timestamp: '2025-12-15T15:30:36.488007'
  training_config_name: snr_range_0_30_perSample_nmse
  training_duration: 6848.088475942612
model_config:
  activation_type: relu
  hidden_dim: 64
  mlp_depth: 3
  model_type: separator1
  num_params: 78480
  num_ports: 6
  num_stages: 2
  pos_values:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  seq_len: 12
  share_weights_across_stages: true
training_config:
  batch_size: 4096
  learning_rate: 0.01
  loss_type: nmse
  num_batches: 1000000
  snr_config:
    max: 30
    min: 0
    num_bins: 10
    per_sample: true
    sampling: stratified
    type: range
  tdl_config:
  - A-30
  - B-100
  - C-300
