model_config:
  hidden_dim: 64
  mlp_depth: 3
  model_type: separator1
  num_ports: 4
  num_stages: 2
  pos_values:
  - 0
  - 3
  - 6
  - 9
  seq_len: 12
  share_weights_across_stages: true
training_config:
  batch_size: 4096
  early_stop_loss: 0.001
  learning_rate: 0.01
  loss_type: nmse
  num_batches: 100
  patience: 5
  print_interval: 100
  save_interval: 1000
  snr_config:
    max: 30
    min: 0
    num_bins: 10
    per_sample: true
    sampling: stratified
    type: range
  tdl_config:
  - A-30
  - B-100
  - C-300
  validation_interval: 100
