tasks:
  channel_separator_4port_quick:
    type: channel_separator
    params:
      seq_len: 12
      pos_values: [0, 3, 6, 9]
      snr_config:
        type: range
        min: 10
        max: 20
        per_sample: false
      tdl_config: A-30

  channel_separator_4port_standard:
    type: channel_separator
    params:
      seq_len: 12
      pos_values: [0, 3, 6, 9]
      snr_config:
        type: range
        min: 0
        max: 30
        per_sample: true
        sampling: stratified
        num_bins: 10
      tdl_config: [A-30, B-100, C-300]

  channel_separator_6port_quick:
    type: channel_separator
    params:
      seq_len: 12
      pos_values: [0, 2, 4, 6, 8, 10]
      snr_config:
        type: range
        min: 10
        max: 20
        per_sample: false
      tdl_config: A-30

  channel_separator_6port_standard:
    type: channel_separator
    params:
      seq_len: 12
      pos_values: [0, 2, 4, 6, 8, 10]
      snr_config:
        type: range
        min: 0
        max: 30
        per_sample: true
        sampling: stratified
        num_bins: 10
      tdl_config: [A-30, B-100, C-300]